services:
  # Serviço do MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rede-social-network

  # Serviço da aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rede_social_app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      EMAIL: ${EMAIL}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - rede-social-network

# Volumes e redes
volumes:
  mysql_data:

networks:
  rede-social-network: